--gtk-version=4
--ozone-platform-hint=auto
--enable-features=UseOzonePlatform,VaapiVideoDecoder,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecodeLinuxGL,VaapiIgnoreDriverChecks,VaapiOnNvidiaGPUs
--disk-cache-dir="$XDG_RUNTIME_DIR/msedge-cache"
