--gtk-version=4
--ozone-platform-hint=auto
--enable-features=UseOzonePlatform,VaapiVideoDecoder,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecodeLinuxGL,VaapiIgnoreDriverChecks,VaapiOnNvidiaGPUs
